name: Agile Complexification Inverter
favicon: null
layout_spectrum: 0.16722
typography_spectrum: 1
title: "David's Agile Complexification Inverter Blog"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d37c13'
    - '#efe2d9'
    - '#3c535b'
    - '#7b8588'
    - '#5f3326'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
