name: Agile Complexification Inverter
favicon: null
layout_spectrum: 0.4172212763223797
typography_spectrum: 0.012955628102645278
title: Agile Complexification Inverter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7681257741060108
  lightness: 0.13107678527012467
  saturation: 0.7534361022990197
  rhythmicContrast: 0.14460755256004632
purpose: []
